### ISSUE TITLE
Add an emotional parameter?

### ISSUE THREAD

**Issue by GitBruno** [LettError/TypeCooker#9]
Psych:

- playful
- energetic
- warm
- provocative
- free
- spirited
- comfortable
- quiet
- loud
- bright
- cheerful
- earnest
- brave
- daring
- confident
- dynamic
- impulsive
- rebellious
- hesitant
- pathetic
- useless
- aggressive
- cold
- reliable
- sympathetic
- clever

With percentages:
40% Brave 60% Warm

Could be easter egg: http://typecooker.com/?level=crazy

**Comment by GitBruno** [comment]
Also what happened to the `As drawn by` `Typedesigner` section?

**Comment by LettError** [comment]
While these are definitely fun to draw, these are also much fuzzier to point to in a drawing.
